# 用语和其他InfoboxEncoder对比的
export CUDA_VISIBLE_DEVICES=3

# Train 
nohup python -u -m table2seq.run_t2s -bridge fusion  -train_data_path_prefix dataset/table_dialogue_res/train -val_data_path_prefix dataset/table_dialogue_res/dev -test_data_path_prefix dataset/table_dialogue_res/test -vocab_path dataset/table_dialogue_res/vocab.txt -field_key_vocab_path dataset/table_dialogue_res/field_key.txt  -mode train -cuda True -hidden_size 512 -embed_size 200 -batch_size 50 -epochs 30 -enc_layers 1 -dec_layers 1 -dual_attn general -field_word_vocab_path dataset/table_dialogue_res/field_word.txt -model_path models/ijcai_2021/HitaGraph -lr 0.0001 -field_tag_usage general  -field_word_tag_path dataset/table_dialogue_res/field_tag.txt  -src_tag_vocab_path dataset/table_dialogue_res/pos_tag.txt   -field_encoder hierarchical_infobox  -enable_field_attn True -enable_query_attn True -copy True -field_copy True -share_copy_attn True -share_field_copy_attn True -infobox_memory_bank_format fwk_fwv_fk -field_input_tags local_pos_fw,local_pos_bw  -mode_selector mlp -add_last_generated_token True  -init_word_vecs True  -unk_learning skip -hierarchical_infobox_rgat_layers 2  -update_decoder_with_global_node True -add_state_to_copy_token True  -copy_query_first True  -char_encoder_type cnn -char_encoders field_key,field_word -hierarchical_infobox_attention True -hierarchical_infobox_attention_type general


# Beam Decoding 
  nohup python -u -m table2seq.run_t2s  -bridge fusion   -train_data_path_prefix dataset/table_dialogue_res/train -val_data_path_prefix dataset/table_dialogue_res/dev -test_data_path_prefix dataset/table_dialogue_res/test -vocab_path dataset/table_dialogue_res/vocab.txt -field_key_vocab_path dataset/table_dialogue_res/field_key.txt  -mode train -cuda True -hidden_size 512 -embed_size 200 -batch_size 32 -epochs 30 -enc_layers 1 -dec_layers 1 -dual_attn general -field_word_vocab_path dataset/table_dialogue_res/field_word.txt -model_path models/ijcai_2021/HitaGraph -lr 0.0001  -field_tag_usage general  -field_word_tag_path dataset/table_dialogue_res/field_tag.txt  -src_tag_vocab_path dataset/table_dialogue_res/pos_tag.txt   -field_encoder hierarchical_infobox    -mode_selector mlp -add_last_generated_token True  -init_word_vecs True  -unk_learning skip  -enable_field_attn True -enable_query_attn True -copy True -field_copy True   -share_copy_attn True -share_field_copy_attn True   -infobox_memory_bank_format fwk_fwv_fk  -field_input_tags local_pos_fw,local_pos_bw -mode infer -beam_width 10  -hierarchical_infobox_rgat_layers 2  -update_decoder_with_global_node True -add_state_to_copy_token True -copy_query_first True  -char_encoder_type cnn -char_encoders field_key,field_word -hierarchical_infobox_attention True -hierarchical_infobox_attention_type general -beam_length_penalize avg  -disable_multiple_copy True -penalize_repeat_tokens_rate 2.0 &
